-- DROP USER MOGESDOC;

CREATE USER MOGESDOC
-- IDENTIFIED BY <password>
;

CREATE TABLE "MOGESDOC"."AGENCIA" 
   (	"ID_AGENCIA" NUMBER(8,0) NOT NULL ENABLE, 
	"CODIGO_AGENCIA" VARCHAR2(8) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(128) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(2) NOT NULL ENABLE, 
	"UNIDAD" NUMBER(8,0) NOT NULL ENABLE, 
	"MUNICIPIO" NUMBER(4,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_AGENCIA" PRIMARY KEY ("ID_AGENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CODIGO_AGENCIA" UNIQUE ("CODIGO_AGENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "MOGESDOC"."AGENCIA" ADD CONSTRAINT "REL_UNIDAD" FOREIGN KEY ("UNIDAD")
	  REFERENCES "MOGESDOC"."UNIDAD" ("ID_UNIDAD") ENABLE;
  ALTER TABLE "MOGESDOC"."AGENCIA" ADD CONSTRAINT "REL_MUNICIPIO_AGENCIA" FOREIGN KEY ("MUNICIPIO")
	  REFERENCES "MOGESDOC"."MUNICIPIO" ("ID_MUNICIPIO") ENABLE;

CREATE INDEX "MOGESDOC"."IX_Relationship14" ON "MOGESDOC"."AGENCIA" ("UNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE INDEX "MOGESDOC"."IX_Relationship15" ON "MOGESDOC"."AGENCIA" ("MUNICIPIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."PK_AGENCIA" ON "MOGESDOC"."AGENCIA" ("ID_AGENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."CODIGO_AGENCIA" ON "MOGESDOC"."AGENCIA" ("CODIGO_AGENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."AREA" 
   (	"ID_AREA" NUMBER(8,0) NOT NULL ENABLE, 
	"CODIGO_AREA" VARCHAR2(8) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(128) NOT NULL ENABLE, 
	"ORGANIZACION" NUMBER(4,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_AREA" PRIMARY KEY ("ID_AREA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CODIGO_AREA" UNIQUE ("CODIGO_AREA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "MOGESDOC"."AREA" ADD CONSTRAINT "REL_ORGANIZACION" FOREIGN KEY ("ORGANIZACION")
	  REFERENCES "MOGESDOC"."ORGANIZACION" ("ID_ORGANIZACION") ENABLE;

CREATE INDEX "MOGESDOC"."IX_Relationship10" ON "MOGESDOC"."AREA" ("ORGANIZACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."PK_AREA" ON "MOGESDOC"."AREA" ("ID_AREA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."CODIGO_AREA" ON "MOGESDOC"."AREA" ("CODIGO_AREA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."BITACORA_DOCUMENTO" 
   (	"ID_BITACORA" NUMBER(8,0) NOT NULL ENABLE, 
	"FECHA_REGISTRO" DATE NOT NULL ENABLE, 
	"TIPO_ACCION" NUMBER(4,0) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(128), 
	"USUARIO" NUMBER(13,0) NOT NULL ENABLE, 
	"DOCUMENTO" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_BITACORA_DOCUMENTO" PRIMARY KEY ("ID_BITACORA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "MOGESDOC"."BITACORA_DOCUMENTO" ADD CONSTRAINT "REL_DOCUMENTO_BITACORA" FOREIGN KEY ("DOCUMENTO")
	  REFERENCES "MOGESDOC"."DOCUMENTO" ("ID_DOCUMENTO") ENABLE;
  ALTER TABLE "MOGESDOC"."BITACORA_DOCUMENTO" ADD CONSTRAINT "REL_USUARIO_BITACORA" FOREIGN KEY ("USUARIO")
	  REFERENCES "MOGESDOC"."USUARIO" ("USUARIO") ENABLE;

CREATE INDEX "MOGESDOC"."IX_Relationship8" ON "MOGESDOC"."BITACORA_DOCUMENTO" ("DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE INDEX "MOGESDOC"."IX_Relationship9" ON "MOGESDOC"."BITACORA_DOCUMENTO" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."PK_BITACORA_DOCUMENTO" ON "MOGESDOC"."BITACORA_DOCUMENTO" ("ID_BITACORA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."CORRESPONDENCIA" 
   (	"ID_CORRESPONDENCIA" NUMBER(8,0) NOT NULL ENABLE, 
	"FECHA_CREACION" DATE NOT NULL ENABLE, 
	"PRIORIDAD" NUMBER(2,0) NOT NULL ENABLE, 
	"DESTINATARIO" VARCHAR2(128) NOT NULL ENABLE, 
	"REMITENTE" VARCHAR2(128) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(2) NOT NULL ENABLE, 
	"TIPO_CORRESPONDENCIA" NUMBER(4,0) NOT NULL ENABLE, 
	"DOCUMENTO" NUMBER(10,0) NOT NULL ENABLE, 
	"USUARIO_AGENCIA" NUMBER(8,0) NOT NULL ENABLE, 
	"TIPO_MENSAJERIA" NUMBER(4,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_CORRESPONDENCIA" PRIMARY KEY ("ID_CORRESPONDENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "MOGESDOC"."CORRESPONDENCIA" ADD CONSTRAINT "REL_USUARIO_CORRESPONDENCIA" FOREIGN KEY ("USUARIO_AGENCIA")
	  REFERENCES "MOGESDOC"."USUARIO_AGENCIA" ("ID_USUARIO_AGENCIA") ENABLE;
  ALTER TABLE "MOGESDOC"."CORRESPONDENCIA" ADD CONSTRAINT "REL_TIPO_MENSAJERIA" FOREIGN KEY ("TIPO_MENSAJERIA")
	  REFERENCES "MOGESDOC"."TIPO_MENSAJERIA" ("ID_TIPO_MENSAJERIA") ENABLE;
  ALTER TABLE "MOGESDOC"."CORRESPONDENCIA" ADD CONSTRAINT "REL_TIPO_CORRESPONDENCIA" FOREIGN KEY ("TIPO_CORRESPONDENCIA")
	  REFERENCES "MOGESDOC"."TIPO_CORRESPONDENCIA" ("ID_TIPO_CORRESPONDENCIA") ENABLE;
  ALTER TABLE "MOGESDOC"."CORRESPONDENCIA" ADD CONSTRAINT "REL_DOCUMENTO_CORRESPONDENCIA" FOREIGN KEY ("DOCUMENTO")
	  REFERENCES "MOGESDOC"."DOCUMENTO" ("ID_DOCUMENTO") ENABLE;

CREATE INDEX "MOGESDOC"."IX_Relationship18" ON "MOGESDOC"."CORRESPONDENCIA" ("USUARIO_AGENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE INDEX "MOGESDOC"."IX_Relationship19" ON "MOGESDOC"."CORRESPONDENCIA" ("TIPO_MENSAJERIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE INDEX "MOGESDOC"."IX_Relationship20" ON "MOGESDOC"."CORRESPONDENCIA" ("TIPO_CORRESPONDENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE INDEX "MOGESDOC"."IX_Relationship21" ON "MOGESDOC"."CORRESPONDENCIA" ("DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."PK_CORRESPONDENCIA" ON "MOGESDOC"."CORRESPONDENCIA" ("ID_CORRESPONDENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."DEPARTAMENTO" 
   (	"ID_DEPARTAMENTO" NUMBER(4,0) NOT NULL ENABLE, 
	"CODIGO_DEPARTAMENTO" VARCHAR2(8) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(128) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(2) NOT NULL ENABLE, 
	"PAIS" NUMBER(4,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_DEPARTAMENTO" PRIMARY KEY ("ID_DEPARTAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CODIGO_DEPARTAMENTO" UNIQUE ("CODIGO_DEPARTAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "MOGESDOC"."DEPARTAMENTO" ADD CONSTRAINT "REL_PAIS" FOREIGN KEY ("PAIS")
	  REFERENCES "MOGESDOC"."PAIS" ("ID_PAIS") ENABLE;

CREATE INDEX "MOGESDOC"."IX_Relationship12" ON "MOGESDOC"."DEPARTAMENTO" ("PAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."PK_DEPARTAMENTO" ON "MOGESDOC"."DEPARTAMENTO" ("ID_DEPARTAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."CODIGO_DEPARTAMENTO" ON "MOGESDOC"."DEPARTAMENTO" ("CODIGO_DEPARTAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."DETALLE_CORRESPONDENCIA" 
   (	"ID_DETALLE_CORRES" NUMBER(8,0) NOT NULL ENABLE, 
	"FECHA_MODIFICACION" DATE NOT NULL ENABLE, 
	"ESTADO_ANTERIOR" VARCHAR2(2) NOT NULL ENABLE, 
	"CORRESPONDENCIA" NUMBER(8,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_DETALLE_CORRESPONDENCIA" PRIMARY KEY ("ID_DETALLE_CORRES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "MOGESDOC"."DETALLE_CORRESPONDENCIA" ADD CONSTRAINT "REL_CORRESPONDENCIA_DETALLE" FOREIGN KEY ("CORRESPONDENCIA")
	  REFERENCES "MOGESDOC"."CORRESPONDENCIA" ("ID_CORRESPONDENCIA") ENABLE;

CREATE INDEX "MOGESDOC"."IX_Relationship22" ON "MOGESDOC"."DETALLE_CORRESPONDENCIA" ("CORRESPONDENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."PK_DETALLE_CORRESPONDENCIA" ON "MOGESDOC"."DETALLE_CORRESPONDENCIA" ("ID_DETALLE_CORRES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."DOCUMENTO" 
   (	"ID_DOCUMENTO" NUMBER(10,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(128) NOT NULL ENABLE, 
	"EXTENSION" VARCHAR2(4) NOT NULL ENABLE, 
	"AUTOR" VARCHAR2(32) NOT NULL ENABLE, 
	"RUTA" VARCHAR2(255) NOT NULL ENABLE, 
	"FECHA_CREACION" DATE NOT NULL ENABLE, 
	"TIPO_DOCUMENTO" NUMBER(4,0) NOT NULL ENABLE, 
	"PREFIJO" NUMBER(8,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_DOCUMENTO" PRIMARY KEY ("ID_DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "MOGESDOC"."DOCUMENTO" ADD CONSTRAINT "REL_TIPO_DOCUMENTO" FOREIGN KEY ("TIPO_DOCUMENTO")
	  REFERENCES "MOGESDOC"."TIPO_DOCUMENTO" ("ID_TIPO_DOCUMENTO") ENABLE;
  ALTER TABLE "MOGESDOC"."DOCUMENTO" ADD CONSTRAINT "REL_PREFIJO_DOCUMENTO" FOREIGN KEY ("PREFIJO")
	  REFERENCES "MOGESDOC"."PREFIJO_DOCUMENTO" ("ID_PREFIJO_DOCUMENTO") ENABLE;

CREATE INDEX "MOGESDOC"."IX_Relationship6" ON "MOGESDOC"."DOCUMENTO" ("TIPO_DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE INDEX "MOGESDOC"."IX_Relationship7" ON "MOGESDOC"."DOCUMENTO" ("PREFIJO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."PK_DOCUMENTO" ON "MOGESDOC"."DOCUMENTO" ("ID_DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."MUNICIPIO" 
   (	"ID_MUNICIPIO" NUMBER(4,0) NOT NULL ENABLE, 
	"CODIGO_MUNICIPIO" VARCHAR2(8) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(128) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(2) NOT NULL ENABLE, 
	"DEPARTAMENTO" NUMBER(4,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_MUNICIPIO" PRIMARY KEY ("ID_MUNICIPIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CODIGO_MUNICIPIO" UNIQUE ("CODIGO_MUNICIPIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "MOGESDOC"."MUNICIPIO" ADD CONSTRAINT "REL_DEPARTAMENTO" FOREIGN KEY ("DEPARTAMENTO")
	  REFERENCES "MOGESDOC"."DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE;

CREATE UNIQUE INDEX "MOGESDOC"."CODIGO_MUNICIPIO" ON "MOGESDOC"."MUNICIPIO" ("CODIGO_MUNICIPIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE INDEX "MOGESDOC"."IX_Relationship13" ON "MOGESDOC"."MUNICIPIO" ("DEPARTAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."PK_MUNICIPIO" ON "MOGESDOC"."MUNICIPIO" ("ID_MUNICIPIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."ORGANIZACION" 
   (	"ID_ORGANIZACION" NUMBER(4,0) NOT NULL ENABLE, 
	"CODIGO" VARCHAR2(8) NOT NULL ENABLE, 
	"URL" VARCHAR2(128) NOT NULL ENABLE, 
	"TELEFONO" VARCHAR2(16) NOT NULL ENABLE, 
	"PREFIJO_TELEFONO" VARCHAR2(4) NOT NULL ENABLE, 
	"LOGOTIPO" VARCHAR2(128) NOT NULL ENABLE, 
	 CONSTRAINT "PK_ORGANIZACION" PRIMARY KEY ("ID_ORGANIZACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CODIGO" UNIQUE ("CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "MOGESDOC"."PK_ORGANIZACION" ON "MOGESDOC"."ORGANIZACION" ("ID_ORGANIZACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."CODIGO" ON "MOGESDOC"."ORGANIZACION" ("CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."PAIS" 
   (	"ID_PAIS" NUMBER(4,0) NOT NULL ENABLE, 
	"CODIGO_PAIS" VARCHAR2(8) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(128) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(2) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PAIS" PRIMARY KEY ("ID_PAIS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CODIGO_PAIS" UNIQUE ("CODIGO_PAIS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "MOGESDOC"."PK_PAIS" ON "MOGESDOC"."PAIS" ("ID_PAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."CODIGO_PAIS" ON "MOGESDOC"."PAIS" ("CODIGO_PAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."PERFIL" 
   (	"ID_PERFIL" NUMBER(4,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(32) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(2) NOT NULL ENABLE, 
	"FECHA_CREACION" DATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_PERFIL" PRIMARY KEY ("ID_PERFIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "MOGESDOC"."PK_PERFIL" ON "MOGESDOC"."PERFIL" ("ID_PERFIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."PERFIL_PERMISO" 
   (	"ID_PERFIL_PERMISO" NUMBER(8,0) NOT NULL ENABLE, 
	"PERFIL" NUMBER(4,0) NOT NULL ENABLE, 
	"PERMISO" NUMBER(4,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PERFIL_PERMISO" PRIMARY KEY ("ID_PERFIL_PERMISO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "MOGESDOC"."PERFIL_PERMISO" ADD CONSTRAINT "REL_PERFIL" FOREIGN KEY ("PERFIL")
	  REFERENCES "MOGESDOC"."PERFIL" ("ID_PERFIL") ENABLE;
  ALTER TABLE "MOGESDOC"."PERFIL_PERMISO" ADD CONSTRAINT "REL_PERMISO" FOREIGN KEY ("PERMISO")
	  REFERENCES "MOGESDOC"."PERMISO" ("ID_PERMISO") ENABLE;

CREATE INDEX "MOGESDOC"."IX_Relationship3" ON "MOGESDOC"."PERFIL_PERMISO" ("PERFIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE INDEX "MOGESDOC"."IX_Relationship4" ON "MOGESDOC"."PERFIL_PERMISO" ("PERMISO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."PK_PERFIL_PERMISO" ON "MOGESDOC"."PERFIL_PERMISO" ("ID_PERFIL_PERMISO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."PERMISO" 
   (	"ID_PERMISO" NUMBER(4,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(32) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(128), 
	"ESTADO" VARCHAR2(2) NOT NULL ENABLE, 
	"FECHA_CREACION" DATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_PERMISO" PRIMARY KEY ("ID_PERMISO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "MOGESDOC"."PK_PERMISO" ON "MOGESDOC"."PERMISO" ("ID_PERMISO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."PREFIJO_DOCUMENTO" 
   (	"ID_PREFIJO_DOCUMENTO" NUMBER(8,0) NOT NULL ENABLE, 
	"AREA" VARCHAR2(16) NOT NULL ENABLE, 
	"UNIDAD" VARCHAR2(16) NOT NULL ENABLE, 
	"AGENCIA" VARCHAR2(16) NOT NULL ENABLE, 
	"TIPO_PREFIJO" NUMBER(4,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_PREFIJO_DOCUMENTO" PRIMARY KEY ("ID_PREFIJO_DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "MOGESDOC"."PREFIJO_DOCUMENTO" ADD CONSTRAINT "REL_TIPO_PREFIJO" FOREIGN KEY ("TIPO_PREFIJO")
	  REFERENCES "MOGESDOC"."TIPO_PREFIJO" ("ID_TIPO_PREFIJO") ENABLE;

CREATE INDEX "MOGESDOC"."IX_Relationship5" ON "MOGESDOC"."PREFIJO_DOCUMENTO" ("TIPO_PREFIJO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."PK_PREFIJO_DOCUMENTO" ON "MOGESDOC"."PREFIJO_DOCUMENTO" ("ID_PREFIJO_DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."TIPO_CORRESPONDENCIA" 
   (	"ID_TIPO_CORRESPONDENCIA" NUMBER(4,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(128) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(2) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(128), 
	 CONSTRAINT "PK_TIPO_CORRESPONDENCIA" PRIMARY KEY ("ID_TIPO_CORRESPONDENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "MOGESDOC"."PK_TIPO_CORRESPONDENCIA" ON "MOGESDOC"."TIPO_CORRESPONDENCIA" ("ID_TIPO_CORRESPONDENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."TIPO_DOCUMENTO" 
   (	"ID_TIPO_DOCUMENTO" NUMBER(4,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(32) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(128), 
	"ESTADO" VARCHAR2(2) NOT NULL ENABLE, 
	"FECHA_CREACION" DATE, 
	 CONSTRAINT "PK_TIPO_DOCUMENTO" PRIMARY KEY ("ID_TIPO_DOCUMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "MOGESDOC"."PK_TIPO_DOCUMENTO" ON "MOGESDOC"."TIPO_DOCUMENTO" ("ID_TIPO_DOCUMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."TIPO_MENSAJERIA" 
   (	"ID_TIPO_MENSAJERIA" NUMBER(4,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(128) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(128), 
	 CONSTRAINT "PK_TIPO_MENSAJERIA" PRIMARY KEY ("ID_TIPO_MENSAJERIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "MOGESDOC"."PK_TIPO_MENSAJERIA" ON "MOGESDOC"."TIPO_MENSAJERIA" ("ID_TIPO_MENSAJERIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."TIPO_PREFIJO" 
   (	"ID_TIPO_PREFIJO" NUMBER(4,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(32) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(2) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TIPO_PREFIJO" PRIMARY KEY ("ID_TIPO_PREFIJO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "MOGESDOC"."PK_TIPO_PREFIJO" ON "MOGESDOC"."TIPO_PREFIJO" ("ID_TIPO_PREFIJO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."TIPO_USUARIO" 
   (	"ID_TIPO_USUARIO" NUMBER(4,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(32) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(128), 
	"ESTADO" VARCHAR2(2) NOT NULL ENABLE, 
	 CONSTRAINT "PK_TIPO_USUARIO" PRIMARY KEY ("ID_TIPO_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "MOGESDOC"."PK_TIPO_USUARIO" ON "MOGESDOC"."TIPO_USUARIO" ("ID_TIPO_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."UNIDAD" 
   (	"ID_UNIDAD" NUMBER(8,0) NOT NULL ENABLE, 
	"CODIGO_UNIDAD" VARCHAR2(8) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(128) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(128), 
	"ESTADO" VARCHAR2(2) NOT NULL ENABLE, 
	"AREA" NUMBER(8,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_UNIDAD" PRIMARY KEY ("ID_UNIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CODIGO_UNIDAD" UNIQUE ("CODIGO_UNIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "MOGESDOC"."UNIDAD" ADD CONSTRAINT "REL_AREA" FOREIGN KEY ("AREA")
	  REFERENCES "MOGESDOC"."AREA" ("ID_AREA") ENABLE;

CREATE INDEX "MOGESDOC"."IX_Relationship11" ON "MOGESDOC"."UNIDAD" ("AREA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."PK_UNIDAD" ON "MOGESDOC"."UNIDAD" ("ID_UNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."CODIGO_UNIDAD" ON "MOGESDOC"."UNIDAD" ("CODIGO_UNIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."USUARIO" 
   (	"USUARIO" NUMBER(13,0) NOT NULL ENABLE, 
	"CLAVE" VARCHAR2(255) NOT NULL ENABLE, 
	"FECHA_CREACION" DATE NOT NULL ENABLE, 
	"OBSERVACION" VARCHAR2(100), 
	"TIPO_USUARIO" NUMBER(4,0) NOT NULL ENABLE, 
	"PERFIL" NUMBER(4,0) NOT NULL ENABLE, 
	 CONSTRAINT "PK_USUARIO" PRIMARY KEY ("USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "MOGESDOC"."USUARIO" ADD CONSTRAINT "REL_TIPO_USUARIO" FOREIGN KEY ("TIPO_USUARIO")
	  REFERENCES "MOGESDOC"."TIPO_USUARIO" ("ID_TIPO_USUARIO") ENABLE;
  ALTER TABLE "MOGESDOC"."USUARIO" ADD CONSTRAINT "REL_USUARIO_PERFIL" FOREIGN KEY ("PERFIL")
	  REFERENCES "MOGESDOC"."PERFIL" ("ID_PERFIL") ENABLE;

CREATE INDEX "MOGESDOC"."IX_Relationship1" ON "MOGESDOC"."USUARIO" ("TIPO_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE INDEX "MOGESDOC"."IX_Relationship2" ON "MOGESDOC"."USUARIO" ("PERFIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."PK_USUARIO" ON "MOGESDOC"."USUARIO" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;

CREATE TABLE "MOGESDOC"."USUARIO_AGENCIA" 
   (	"ID_USUARIO_AGENCIA" NUMBER(8,0) NOT NULL ENABLE, 
	"USUARIO" NUMBER(13,0) NOT NULL ENABLE, 
	"AGENCIA" NUMBER(8,0) NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(2) NOT NULL ENABLE, 
	"FECHA_CREACION" DATE NOT NULL ENABLE, 
	"FECHA_MODIFICACION" DATE, 
	 CONSTRAINT "PK_USUARIO_AGENCIA" PRIMARY KEY ("ID_USUARIO_AGENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "MOGESDOC"."USUARIO_AGENCIA" ADD CONSTRAINT "REL_USUARIO_AGENCIA" FOREIGN KEY ("USUARIO")
	  REFERENCES "MOGESDOC"."USUARIO" ("USUARIO") ENABLE;
  ALTER TABLE "MOGESDOC"."USUARIO_AGENCIA" ADD CONSTRAINT "REL_AGENCIA_USUARIO" FOREIGN KEY ("AGENCIA")
	  REFERENCES "MOGESDOC"."AGENCIA" ("ID_AGENCIA") ENABLE;

CREATE INDEX "MOGESDOC"."IX_Relationship16" ON "MOGESDOC"."USUARIO_AGENCIA" ("USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE INDEX "MOGESDOC"."IX_Relationship17" ON "MOGESDOC"."USUARIO_AGENCIA" ("AGENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "MOGESDOC"."PK_USUARIO_AGENCIA" ON "MOGESDOC"."USUARIO_AGENCIA" ("ID_USUARIO_AGENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
;
